[package]
name = "sspagbol"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
url = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
crossbeam = "0.8"
crossbeam-channel = "0.5"