[package]
name = "sspagbol"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17"
ansi_term = "0.12"
emojis = "0.7.1"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
url = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"