- name: PiHole
  desc: DNS and ad-blocking service
  cilist:
    - ciname: PiHole Web GUI
      citype: Webserver
      cidata:
        - "https://pihole.afih.net/admin/login"
        - "443"

- name: Deluge
  desc: Torrent client
  cilist:
    - ciname: Deluge Web UI
      citype: Webserver
      cidata:
        - "https://deluge.afih.net/"
        - "443"
