- name: Test Service
  desc: Example service
  cilist:
    - ciname: SSH Connection
      citype: SSHServer
      cidata:
        - "192.168.0.5"
        - "22"
    - ciname: Google Web Server
      citype: Webserver
      cidata:
        - "https://google.com/"
        - "443"
        - "true"  # Verify SSL
    - ciname: Google DNS Server
      citype: DNSServer
      cidata:
        - "8.8.8.8"